services:
  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      default:
        aliases:
          - mailpit

  keycloak:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: keycloak
    restart: unless-stopped
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin@example.com
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_LOG_LEVEL: info
      KC_LOG: console
      KC_LOG_CONSOLE_OUTPUT: json
    ports:
      - 8080:8080
    networks:
      default:
        aliases:
          - keycloak
    command: ["start-dev"]
