version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@7.0.0
jobs:
  build-and-push-ecr:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - aws-ecr/build-and-push-image:
          account-url: "400489187383.dkr.ecr.us-east-1.amazonaws.com"
          region: "us-east-1"
          repo: "kanrix/keycloak"
          tag: "${CIRCLE_SHA1}"
workflows:
  version: 2
  build_and_push:
    jobs:
      - build-and-push-ecr:
          context: aws-ecr-context