version: 2.1
setup: true
orbs:
  path-filtering: circleci/path-filtering@1.2.0  

workflows:
  setup-workflow:
    jobs:
      - path-filtering/filter:
          base-revision: main
          config-path: .circleci/continue-config.yml
          mapping: |
            keycloakify/.* build-keycloak true .circleci/continue-config.yml
            Dockerfile build-keycloak true .circleci/continue-config.yml