# test
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@5.1
  aws-ecr: circleci/aws-ecr@9.0

executors:
  default:
    docker:
      - image: cimg/base:stable

parameters:
  build-keycloak:
    type: boolean
    default: false

jobs:
  keycloak-build-and-deploy:
    executor: default
    steps:
      - checkout
      - aws-cli/setup:
          role-arn: "${AWS_OIDC_ROLE_ARN}"
          region: "${AWS_DEFAULT_REGION}"   
      - run:
          name: Set variables
          command: |
            REPOSITORY_NAME="platform/keycloak"
            REPOSITORY="${ECR_BASE}/${REPOSITORY_NAME}"
            VERSION=2.6-inktavo-$(git rev-parse --short HEAD)
            TAG="${REPOSITORY}:${VERSION}"

            cat ~/.aws/credentials
            echo $REPOSITORY_NAME > /tmp/repo
            echo $TAG > /tmp/tag
      - aws-ecr/build_and_push_image:
          auth:
            - aws-cli/setup:
                role-arn: "${AWS_OIDC_ROLE_ARN}"
                region: "${AWS_DEFAULT_REGION}"
          create_repo: true
          dockerfile: Dockerfile
          path: .
          platform: linux/x86_64
          push_image: true
          region: "${AWS_DEFAULT_REGION}"
          repo: test_circleci
          tag: "$(cat /tmp/tag)"
      - aws-ecr/push_image:
          region: "${AWS_DEFAULT_REGION}"
          repo: test_circleci
          tag: "$(cat /tmp/tag)"       

only-main: &only-main
  filters:
    branches:
      only: main

workflows:
  keycloak-staging-deploy:
    when: << pipeline.parameters.build-keycloak >>
    jobs:
      - keycloak-build-and-deploy:
          context: AWS_STAGING
          <<: *only-main
