# test
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@5.1
  aws-ecr: circleci/aws-ecr@9.0

executors:
  default:
    docker:
      - image: cimg/base:stable

parameters:
  build-keycloak:
    type: boolean
    default: false

jobs:
  keycloak-build-and-deploy:
    executor: default
    steps:
      - checkout
      - aws-cli/setup:
          profile_name: context_based      
      - run:
          name: Check if the build is necessary
          command: |
            REPOSITORY_NAME="platform/keycloak"
            REPOSITORY="${ECR_BASE}/${REPOSITORY_NAME}"
            VERSION=2.6-inktavo-$(git rev-parse --short HEAD)
            TAG="${REPOSITORY}:${VERSION}"

            aws configure list-profiles
            TAG_EXISTS=$(aws ecr list-images --profile context_based --repository-name "${REPOSITORY_NAME}" --query 'imageIds[*].imageTag' --output text | grep -w "${VERSION}")

            if [ -z "$TAG_EXISTS" ]; then
              echo $REPOSITORY_NAME > /tmp/repo
              echo $TAG > /tmp/tag
            else
              echo "Tag exists, skipping"
              circleci-agent step halt
            fi
      - aws-ecr/build_and_push_image:
          auth:
            - aws-cli/setup:
                profile_name: context_based
          create_repo: true
          dockerfile: Dockerfile
          path: .
          platform: linux/x86_64
          push_image: true
          region: "${AWS_DEFAULT_REGION}"
          repo: test_circleci
          tag: "$(cat /tmp/tag)"

only-main: &only-main
  filters:
    branches:
      only: main

workflows:
  keycloak-staging-deploy:
    when: 
      - << pipeline.parameters.build-keycloak >>   
    jobs:
      - keycloak-build-and-deploy:
          context: AWS_STAGING
          <<: *only-main
