# test
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@5.2
  aws-ecr: circleci/aws-ecr@9.4
  slack: circleci/slack@5.1.1

parameters:
  build-keycloak:
    type: boolean
    default: false

jobs:
  keycloak-build-and-deploy:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - aws-cli/setup:
          profile_name: oidc_profile
          role_arn: "${AWS_OIDC_ROLE_ARN}"
          region: "${AWS_DEFAULT_REGION}"   
      - run:
          name: Set variables
          command: |
            REPOSITORY_NAME="platform/keycloak_379"
            VERSION=2.6-inktavo-$(git rev-parse --short HEAD)
            
            echo $REPOSITORY_NAME > /tmp/repo
            echo $VERSION > /tmp/version
      - aws-ecr/build_and_push_image:
          auth:
            - aws-cli/setup:
                profile_name: oidc_profile
                role_arn: "${AWS_OIDC_ROLE_ARN}"
                region: "${AWS_DEFAULT_REGION}"
          profile_name: oidc_profile
          create_repo: true
          dockerfile: Dockerfile
          path: .
          platform: linux/amd64
          push_image: true
          skip_when_tags_exist: true
          region: "${AWS_DEFAULT_REGION}"
          repo: "$(cat /tmp/repo)"
          tag: "$(cat /tmp/version),latest"
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1          

only-main: &only-main
  filters:
    branches:
      only: main

workflows:
  keycloak-staging-deploy:
    when: << pipeline.parameters.build-keycloak >>
    jobs:
      - manual-deploy?:
          <<: *only-main
          type: approval    
      - keycloak-build-and-deploy:
          context:
            - AWS_STAGING
            - SLACK
          <<: *only-main
          requires:
            - manual-deploy?
