# test
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@5.2
  aws-ecr: circleci/aws-ecr@9.4

executors:
  default:
    docker:
      - image: cimg/base:stable

parameters:
  build-keycloak:
    type: boolean
    default: false

jobs:
  keycloak-build-and-deploy:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - aws-cli/setup:
          profile_name: oidc_profile
          role_arn: "${AWS_OIDC_ROLE_ARN}"
          region: "${AWS_DEFAULT_REGION}"   
      - run:
          name: Set variables
          command: |
            REPOSITORY_NAME="platform/keycloak_379"
            REPOSITORY="${ECR_BASE}/${REPOSITORY_NAME}"
            VERSION=2.6-inktavo-$(git rev-parse --short HEAD)
            TAG="${REPOSITORY}:${VERSION}"

            cat ~/.aws/credentials
            echo $REPOSITORY_NAME > /tmp/repo
            echo $VERSION > /tmp/version
            echo $TAG > /tmp/tag
      - aws-ecr/build_and_push_image:
          auth:
            - aws-cli/setup:
                profile_name: oidc_profile
                role_arn: "${AWS_OIDC_ROLE_ARN}"
                region: "${AWS_DEFAULT_REGION}"
          profile_name: oidc_profile
          create_repo: true
          dockerfile: Dockerfile
          path: .
          platform: linux/amd64
          push_image: true
          region: "${AWS_DEFAULT_REGION}"
          repo: "$(cat /tmp/repo)"
          tag: "$(cat /tmp/version)"
      - aws-ecr/push_image:
          region: "${AWS_DEFAULT_REGION}"
          repo: "$(cat /tmp/repo)"
          tag: "$(cat /tmp/version)"       

only-main: &only-main
  filters:
    branches:
      only: main

workflows:
  keycloak-staging-deploy:
    when: << pipeline.parameters.build-keycloak >>
    jobs:
      - keycloak-build-and-deploy:
          context: AWS_STAGING
          <<: *only-main
